version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - echo "Install process starting ..."
      - npm install
      - echo "Install process finished!"
  build:
    commands:
      - echo "Build process starting now ..."
      - npm run build-storybook
      - echo "Build process finished!"
artifacts:
  name: tind-2-storybook-latest.zip
  base-directory: storybook-static
  files:
    - '**/*'
